name: build

on:
  push:
    branches: 'master'
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/${{ github.repository }}
          tag-sha: true
          tag-semver: |
            {{version}}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v2
        
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
