name: build

on:
  push:
    branches: 'master'
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
          else
            echo ::set-output name=version::snapshot
          fi
          echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v2
        
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/vchrisb/e3dc-forecast:latest
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      -
        name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}
      -
        name: Clear
        run: |
          rm -f ${HOME}/.docker/config.json
